### ISSUE TITLE
Unable to load samples/jsonrpc.* files

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode-lsif-extension#24]
Probably because the samples were created with an older LSIF version. I can see that jsonrpc.lsif was created with LSIF version 0.3.1
- `No project root provided` message in Output when trying to load jsonrpc.lsif
- `Can't create database for lsif:/c%3A/XXX/samples/jsonrpc.db` when trying to load jsonrpc.db

**Comment by dbaeumer** [comment]
Correct. I will create new ones. Thanks for pointing this out!
