### ISSUE TITLE
Still unable to load samples/jsonrpc.db file

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode-lsif-extension#25]
Even after the fix for #24 I still can't open the sample database:
```
[Error - 14:36:06] Can't create database for lsif:/c%3A/Users/...
```

After I modified https://github.com/microsoft/vscode-lsif-extension/blob/42be1c8c414f614ffaa9a285108bfe378454c0c9/server/src/lsifServer.ts#L135-L137

by adding this line to the catch block:
```
		connection.console.error(_error.message);
```

I got this:
```
[Error - 14:36:06] The module '\\?\c:\Users\XXX\Documents\GitHub\XXX\vscode-lsif-extension\server\node_modules\better-sqlite3\build\Release\better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 85. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```

I am building and testing with this:
```
Version: 1.55.0-insider (user setup)
Commit: c185983a683d14c396952dd432459097bc7f757f
Date: 2021-03-30T12:48:52.547Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042
```

**Comment by dbaeumer** [comment]
@gjsjohnmurray which node version do you have installed on your system? It must match the node version of the Electron (e.g. 12.18.3) when you run npm install. Otherwise the binaries don't match. Sorry for that. I should convert this to yarn which allows configuring this.

**Comment by gjsjohnmurray** [comment]
@dbaeumer in my VS Code Terminal `node --version` was reporting `v12.18.4`, so I uninstalled it and reinstalled 12.18.3. Now `node --version` reports the version matching the one VS Code is using, but I still get the problem. 

To me the error message suggests a mismatch with what the better-sqlite3 package is built with. But I'm not an expert in this area.

**Comment by dbaeumer** [comment]
Yes, but the better SQLite should be built during npm install. Let me see if there is a problem with that under Windows. I usually run everything in WSL :-)

**Comment by dbaeumer** [comment]
@gjsjohnmurray I guess I fixed it. Can you pull, run `git clean -xfd .` in the workspace root and then `npm install` again.

Please ping if it didn't fix it. It works for me now under Windows.

**Comment by gjsjohnmurray** [comment]
@dbaeumer yes, all fine now. Thanks!
